uvmf:
  environments:
    memaccess:
      agents:
      - initiator_responder: INITIATOR
        name: agent_in
        type: memaccess_in
      - initiator_responder: INITIATOR
        name: agent_out
        type: memaccess_out
      analysis_components:
      - name: pred
        parameters: []
        type: memaccess_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scbd
        sb_type: uvmf_in_order_scoreboard
        trans_type: memaccess_out_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_in.monitored_ap
        receiver: pred.analysis_export
        validate: 'True'
      - driver: pred.analysis_port
        receiver: scbd.expected_analysis_export
        validate: 'True'
      - driver: agent_out.monitored_ap
        receiver: scbd.actual_analysis_export
        validate: 'True'
